In [318]:
import pandas as pd
from collections import defaultdict
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import math
from keras.layers import Flatten

In [23]:
# does not contain 'H' or 'AB' data
condensed_df = pd.read_csv('src/data/condensed.csv')

In [26]:
condensed_df.columns

Index(['playerID', 'year1_2B', 'year1_3B', 'year1_BB', 'year1_CS', 'year1_G',
       'year1_GIDP', 'year1_HBP', 'year1_HR', 'year1_IBB',
       ...
       'year7_SF', 'year7_SH', 'year7_SO', 'year7_avg', 'pos_1B', 'pos_2B',
       'pos_3B', 'pos_C', 'pos_OF', 'pos_SS'],
      dtype='object', length=119)

In [27]:
six_year_cols = [col for col in condensed_df.columns if 'year7' not in col]
six_year_df = condensed_df[six_year_cols]
y = condensed_df['year7_avg']

In [82]:
six_year_df2 = six_year_df.astype(float)

In [439]:
uncondensed_df = pd.read_csv('src/data/uncondensed.csv')
uncondensed_df.drop('Unnamed: 0', axis=1, inplace=True)
uncondensed_df = pd.get_dummies(uncondensed_df, columns=['pos'])

In [440]:
uncondensed_df.drop('yearID', axis=1, inplace=True)
uncondensed_df.set_index('playerID', inplace=True)

In [441]:
uncondensed_df = uncondensed_df.astype(float)
uncondensed_df

G      R    2B    3B    HR    RBI    SB    CS     BB     SO  \
playerID                                                                     
aaronha01  122.0   58.0  27.0   6.0  13.0   69.0   2.0   2.0   28.0   39.0   
aaronha01  153.0  105.0  37.0   9.0  27.0  106.0   3.0   1.0   49.0   61.0   
aaronha01  153.0  106.0  34.0  14.0  26.0   92.0   2.0   4.0   37.0   54.0   
aaronha01  151.0  118.0  27.0   6.0  44.0  132.0   1.0   1.0   57.0   58.0   
aaronha01  153.0  109.0  34.0   4.0  30.0   95.0   4.0   1.0   59.0   49.0   
aaronha01  154.0  116.0  46.0   7.0  39.0  123.0   8.0   0.0   51.0   54.0   
aaronha01  153.0  102.0  20.0  11.0  40.0  126.0  16.0   7.0   60.0   63.0   
abbotku01  101.0   41.0  17.0   3.0   9.0   33.0   3.0   0.0   16.0   98.0   
abbotku01  120.0   60.0  18.0   7.0  17.0   60.0   4.0   3.0   36.0  110.0   
abbotku01  109.0   37.0  18.0   7.0   8.0   33.0   3.0   3.0   22.0   99.0   
abbotku01   94.0   35.0  18.0   2.0   6.0   30.0   3.0   1.0   14.0   68.0   
abbotku01   77.0   26.0  13.0   1.0   5.0   24.0   2.0   1.0   12.0   53.0   
abbotku01   96.0   41.0  17.0   2.0   8.0   41.0   3.0   2.0   16.0   69.0   
abbotku01   79.0   22.0   7.0   1.0   6.0   12.0   1.0   1.0   14.0   51.0   
abreubo01   59.0   22.0  10.0   2.0   3.0   26.0   7.0   2.0   21.0   48.0   
abreubo01  151.0   68.0  29.0   6.0  17.0   74.0  19.0  10.0   84.0  133.0   
abreubo01  152.0  118.0  35.0  11.0  20.0   93.0  27.0   9.0  109.0  113.0   
abreubo01  154.0  103.0  42.0  10.0  25.0   79.0  28.0   8.0  100.0  116.0   
abreubo01  162.0  118.0  48.0   4.0  31.0  110.0  36.0  14.0  106.0  137.0   
abreubo01  157.0  102.0  50.0   6.0  20.0   85.0  31.0  12.0  104.0  117.0   
abreubo01  158.0   99.0  35.0   1.0  20.0  101.0  22.0   9.0  109.0  126.0   
adairje01  133.0   41.0  21.0   1.0   9.0   37.0   5.0   2.0   35.0   51.0   
adairje01  139.0   67.0  29.0   4.0  11.0   48.0   7.0   7.0   27.0   77.0   
adairje01  109.0   34.0  21.0   3.0   6.0   30.0   3.0   3.0    9.0   51.0   
adairje01  155.0   56.0  20.0   3.0   9.0   47.0   3.0   2.0   28.0   72.0   
adairje01  157.0   51.0  26.0   3.0   7.0   66.0   6.0   4.0   35.0   65.0   
adairje01  122.0   30.0  19.0   2.0   4.0   39.0   3.0   2.0   21.0   52.0   
adairje01  117.0   47.0  17.0   1.0   3.0   35.0   1.0   5.0   17.0   52.0   
adamsbo03   94.0   35.0  13.0   3.0   4.0   24.0  16.0   0.0   18.0   32.0   
adamsbo03   81.0   39.0  11.0   2.0   4.0   20.0   9.0   0.0   25.0   23.0   
...          ...    ...   ...   ...   ...    ...   ...   ...    ...    ...   
zimmedo01  128.0   57.0  25.0   4.0  13.0   40.0   5.0   1.0   25.0   70.0   
zimmedo01   77.0   19.0  12.0   2.0   2.0   17.0   1.0   3.0   17.0   40.0   
zimmehe01   46.0   17.0   4.0   1.0   0.0    9.0   2.0   0.0    1.0    0.0   
zimmehe01   65.0   23.0   9.0   2.0   0.0   21.0   7.0   0.0    3.0    0.0   
zimmehe01   99.0   35.0  16.0   6.0   3.0   38.0   7.0   0.0   20.0   36.0   
zimmehe01  143.0   80.0  22.0  17.0   9.0   85.0  23.0   0.0   25.0   50.0   
zimmehe01  145.0   95.0  41.0  14.0  14.0   99.0  23.0   0.0   38.0   60.0   
zimmehe01  127.0   69.0  28.0  12.0   9.0   95.0  18.0   0.0   41.0   40.0   
zimmehe01  146.0   75.0  36.0  12.0   4.0   87.0  17.0   0.0   20.0   46.0   
zimmery01  157.0   84.0  47.0   3.0  20.0  110.0  11.0   8.0   61.0  120.0   
zimmery01  162.0   99.0  43.0   5.0  24.0   91.0   4.0   1.0   61.0  125.0   
zimmery01  106.0   51.0  24.0   1.0  14.0   51.0   1.0   1.0   31.0   71.0   
zimmery01  157.0  110.0  37.0   3.0  33.0  106.0   2.0   0.0   72.0  119.0   
zimmery01  142.0   85.0  32.0   0.0  25.0   85.0   4.0   1.0   69.0   98.0   
zimmery01  101.0   52.0  21.0   2.0  12.0   49.0   3.0   1.0   41.0   73.0   
zimmery01  145.0   93.0  36.0   1.0  25.0   95.0   5.0   2.0   57.0  116.0   
ziskri01   103.0   44.0  23.0   7.0  10.0   54.0   0.0   0.0   21.0   63.0   
ziskri01   149.0   75.0  30.0   3.0  17.0  100.0   1.0   1.0   65.0   91.0   
ziskri01   147.0   69.0  27.0   3.0  

In [404]:
# X = uncondensed_df.groupby('playerID').apply(lambda x: x.iloc[:-1, :]).reset_index(0, drop=True)

# y = uncondensed_df.groupby('playerID').apply(lambda x: x.iloc[-1, :])

# y = pd.DataFrame(y['avg'])
# y

avg
playerID           
aaronha01  0.291525
abbotku01  0.216561
abreubo01  0.299827
adairje01  0.270531
adamsbo03  0.282575
adamssp01  0.260204
adcocjo01  0.290749
ageeto01   0.227488
ainsmed01  0.191429
aldremi01  0.266667
alfoned01  0.242888
alicelu01  0.252577
allenbe01  0.246575
allendi01  0.278867
allenet01  0.241379
alleyge01  0.244131
allisbo01  0.232877
allisdo01  0.147826
almonbi01  0.266075
alomaro01  0.306122
alomasa01  0.238298
alomasa02  0.263158
aloufe01   0.253012
alouje01   0.305677
alouma01   0.331541
aloumo01   0.311644
altmage01  0.234694
altuvjo01  0.345763
alvarpe01  0.249258
alvisma01  0.225131
...             ...
wynnji01   0.268687
wyrosjo01  0.264637
yastrca01  0.326425
yeagejo01  0.238532
yeagest01  0.192982
yorkru01   0.271454
yorkto01   0.282700
yosted01   0.272097
youklke01  0.257541
youngch04  0.200000
youngde03  0.266551
youngdm01  0.297153
younger01  0.285398
youngjo02  0.292225
youngke01  0.297945
youngmi02  0.314554
youngra01  0.299252
youngro01  0.355513
yountro01  0.292962
zarilal01  0.324841
zaungr01   0.221622
zeidero01  0.234783
zeileto01  0.262561
zernigu01  0.254237
zimmech01  0.284457
zimmedo01  0.213115
zimmehe01  0.296099
zimmery01  0.282007
ziskri01   0.262425
zobribe01  0.274510

[2348 rows x 1 columns]

In [442]:
def dict_convert(df):
    def_dict = defaultdict(dict)
    for i in range(7):
        year = 'year' + str(i + 1)
        def_dict[year] = df.groupby('playerID').nth(i).T.to_dict('index')
    return def_dict

In [443]:
y_values = uncondensed_df.pop('avg')

In [444]:
X_panel = pd.Panel(dict_convert(uncondensed_df))
y_panel = pd.Panel(dict_convert(pd.DataFrame(y_values)))

(16436,)

In [446]:
X_data = X_panel.as_matrix().astype('float32')
y_data = y_panel.as_matrix()
print(X_data.shape, y_data.shape)

(7, 2348, 21) (7, 2348, 1)


In [447]:
# scaler = MinMaxScaler(feature_range=(0, 2))
# data_norm = scaler.fit_transform(dataset.reshape(dataset.shape[0], -1)).reshape(dataset.shape)

In [448]:
X_new_data = np.moveaxis(X_data, 0, 1)
y_new_data = np.moveaxis(y_data, 0, 1)
print(X_new_data.shape, y_new_data.shape)

(2348, 7, 21) (2348, 7, 1)


In [410]:
X_new_data[0, :, 0]

array([27., 37., 34., 27., 34., 46., nan], dtype=float32)

In [449]:
X_train, X_test, y_train, y_test = train_test_split(X_new_data, y_new_data)

In [450]:
y_test

array([[[0.28818444],
        [0.28705882],
        [0.2690678 ],
        ...,
        [0.26908397],
        [0.28762542],
        [0.2244489 ]],

       [[0.28150573],
        [0.24525316],
        [0.25988701],
        ...,
        [0.28692699],
        [0.23333333],
        [0.21988528]],

       [[0.2244898 ],
        [0.2962963 ],
        [0.22358722],
        ...,
        [0.2251816 ],
        [0.20740741],
        [0.2816092 ]],

       ...,

       [[0.29064039],
        [0.26259947],
        [0.29650092],
        ...,
        [0.30167598],
        [0.28729282],
        [0.31165919]],

       [[0.25619835],
        [0.29133858],
        [0.26      ],
        ...,
        [0.23370787],
        [0.26262626],
        [0.2195122 ]],

       [[0.3125    ],
        [0.27740492],
        [0.26130653],
        ...,
        [0.27130435],
        [0.24587156],
        [0.30927835]]])

In [451]:
y_train = y_train[:,6,:] # grab only the last column of BAs
y_test = y_test[:,6,:]
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(1761, 7, 21)
(1761, 1)
(587, 7, 21)
(587, 1)


In [453]:
model = Sequential()
model.add(LSTM(4, input_shape=(7, 21)))
model.add(Dense(7))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X_train, y_train, verbose=1, epochs=5, batch_size=1)

Epoch 1/5
1761/1761 [==============================] - 12s 7ms/step - loss: 0.0037
Epoch 2/5
1761/1761 [==============================] - 11s 6ms/step - loss: 0.0014
Epoch 3/5
1761/1761 [==============================] - 11s 6ms/step - loss: 0.0014
Epoch 4/5
1761/1761 [==============================] - 11s 6ms/step - loss: 0.0012
Epoch 5/5
1761/1761 [==============================] - 11s 6ms/step - loss: 0.0012


In [454]:
trainPred = model.predict(X_train)
testPred = model.predict(X_test)

In [455]:
print(trainPred.shape)
print(testPred.shape)

(1761, 1)
(587, 1)


In [456]:
print(y_test.shape)
print(testPred.shape)

(587, 1)
(587, 1)


In [457]:
testScore = math.sqrt(mean_squared_error(y_test, testPred))
trainScore = math.sqrt(mean_squared_error(y_train, trainPred))
print('Test Score: {:.3f}'.format(testScore))
print('Train Score: {:.3f}'.format(trainScore))

Test Score: 0.033
Train Score: 0.034


In [459]:
model.evaluate(X_test, y_test)

587/587 [==============================] - 1s 1ms/step


0.0011166594076697006

In [466]:
X_train[0,1,:]

array([ 15.,   2.,  25.,   4., 127.,   0.,   1.,   0.,   0.,  41.,  46.,
        13.,   0.,  11.,  27.,   0.,   0.,   0.,   0.,   0.,   1.],
      dtype=float32)

In [461]:
y_train

array([[0.24152542],
       [0.24017467],
       [0.30353818],
       ...,
       [0.27613941],
       [0.25384615],
       [0.24161074]])